99XT.InventoryControl.App/Controllers/InventoryController.cs
using _99XT.InventoryControl.Core.ICore;
using _99XT.InventoryControl.LoggerService.ILoggerCore;
using _99XT.InventoryControl.Models.View_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace _99XT.InventoryControl.App.Controllers
{
    [Authorize]
    public class InventoryController : Controller
    {
        private readonly IInventoryCore _inventoryCore;
        private readonly ISupplierCore _supplierCore;
        private ILoggerManager _logger;

        public InventoryController(IInventoryCore inventoryCore, ISupplierCore supplierCore, ILoggerManager logger)
        {
            _inventoryCore = inventoryCore;
            _supplierCore = supplierCore;
            _logger = logger;
        }

        // GET: Inventory
        public async Task<IActionResult> Index()
        {
            return View(await _inventoryCore.GetAllProducts());
        }

        // GET: Inventory/Details/5
        public async Task<IActionResult> Details(long id)
        {
            var product = await _inventoryCore.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Inventory/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ProductViewModel viewModel = new ProductViewModel
            {
                AllSuppliers = await _supplierCore.GetAllSuppliers()
            };
            return View(viewModel);
        }

        // POST: Inventory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                var savedProduct = await _inventoryCore.AddProduct(productViewModel.Product);
                return RedirectToAction(nameof(Index));
            }
            return View(productViewModel.Product);
        }

        // GET: Inventory/Edit/5
        public async Task<IActionResult> Edit(long id)
        {
            ProductViewModel viewModel = new ProductViewModel
            {
                Product = await _inventoryCore.GetProductById(id),
                AllSuppliers = await _supplierCore.GetAllSuppliers()
            };
            if (viewModel.Product == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // POST: Inventory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _inventoryCore.UpdateProduct(productViewModel.Product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(productViewModel.Product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productViewModel.Product);
        }

        // GET: Inventory/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long id)
        {
            var product = await _inventoryCore.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Inventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            try
            {
                await _inventoryCore.DeleteProduct(id);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception e)
            {

                throw;
            }

        }

        private bool ProductExists(long id)
        {
            return _inventoryCore.DoesProductExist(id);
        }

    }
}

99XT.InventoryControl.App/Controllers/SupplierController.cs
using _99XT.InventoryControl.Core.ICore;
using _99XT.InventoryControl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace _99XT.InventoryControl.App.Controllers
{
    [Authorize]
    public class SupplierController : Controller
    {
        private readonly ISupplierCore _supplierCore;

        public SupplierController(ISupplierCore _core)
        {
            _supplierCore = _core;
        }

        // GET: Supplier
        public async Task<IActionResult> Index()
        {
            return View(await _supplierCore.GetAllSuppliers());
        }

        // GET: Supplier/Details/5
        public async Task<IActionResult> Details(long id)
        {
            var supplier = await _supplierCore.GetSupplierById(id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Supplier/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Supplier/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("SupplierId,Name,AddressLine1,AddressLine2,Telephone,DateAdded,DateModified")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                await _supplierCore.AddSupplier(supplier);
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Supplier/Edit/5
        public async Task<IActionResult> Edit(long id)
        {
            var supplier = await _supplierCore.GetSupplierById(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Supplier/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("SupplierId,Name,AddressLine1,AddressLine2,Telephone,DateAdded,DateModified")] Supplier supplier)
        {
            if (id != supplier.SupplierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _supplierCore.UpdateSupplier(supplier);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Supplier/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(long id)
        {
            var supplier = await _supplierCore.GetSupplierById(id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Supplier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            await _supplierCore.DeleteSupplier(id);
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(long id)
        {
            return _supplierCore.DoesSupplierExist(id);
        }
    }
}

99XT.InventoryControl.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 99XT Inventory Control App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inventory Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Index">Manage Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Manage Suppliers</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - 99XT Inventory Control App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>